from __future__ import annotations

from pathlib import Path
import sys

from dotenv import load_dotenv


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
load_dotenv(REPO_ROOT / ".env")

from services.image_generator import check_image_backend


def main() -> None:
    try:
        info = check_image_backend()
    except Exception as exc:
        print("IMAGE BACKEND: FAIL")
        print(f"{type(exc).__name__}: {exc}")
        raise SystemExit(2) from exc

    print("IMAGE BACKEND: PASS")
    for key, value in info.items():
        print(f"{key}: {value}")
    print("No image was generated by this check.")


if __name__ == "__main__":
    main()
